language: android
before_install:
  - nvm install 13
  - node --version
  - yes | sdkmanager "platforms;android-28"
  - cd android
  - chmod +x gradlew
  - cd ..
install:
  - npm install
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-19
script:
  - cd android
  - yes | ./gradlew assembleRelease
